display:
  default:
    display_title: 'Por defecto'
    display_options:
      fields:
        comment_bulk_form:
          action_title: Acción
        subject:
          label: Asunto
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Autor
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          label: Actualizado
          separator: ', '
        operations:
          label: Operaciones
        name_1:
          separator: ', '
      pager:
        options:
          tags:
            next: 'siguiente ›'
            previous: '‹ anterior'
            first: '« primero'
            last: 'último »'
          expose:
            items_per_page_label: 'Elementos por página'
            items_per_page_options_all_label: '- Todo -'
            offset_label: Desplazamiento
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        subject:
          expose:
            label: Asunto
        combine:
          expose:
            label: 'Nombre del autor'
        langcode:
          expose:
            label: Idioma
  page_unapproved:
    display_options:
      fields:
        comment_bulk_form:
          action_title: Acción
        subject:
          label: Asunto
          separator: ', '
        uid:
          separator: ', '
        name:
          label: Autor
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          label: Actualizado
          separator: ', '
        operations:
          label: Operaciones
        name_1:
          separator: ', '
      filters:
        subject:
          expose:
            label: Asunto
        langcode:
          expose:
            label: Idioma
