display:
  default:
    display_options:
      pager:
        options:
          tags:
            next: 'siguiente ›'
            previous: '‹ anterior'
            first: '« primera'
            last: 'última »'
      header:
        result:
          content: 'Mostrando @start - @end de <span class="badge">@total</span>'
