display:
  default:
    display_options:
      use_more_text: 'Vea todas las noticias'
      link_url: /es/news
      header:
        area:
          content:
            value: "<p><a class=\"recent-button\" href=\"/es/news\">Noticias recientes</a></p>\r\n"
            format: full_html
