_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  addtoany: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  block: 0
  block_content: 0
  blog_posts: 0
  breakpoint: 0
  calendar: 0
  calendar_datetime: 0
  captcha: 0
  ckeditor: 0
  comment: 0
  components: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_translation: 0
  contextual: 0
  csv_importer: 0
  csv_serialization: 0
  ctools: 0
  custom_pub: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  diff: 0
  download_dataset: 0
  download_indicator: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  emulsify_twig: 0
  entity_print: 0
  events: 0
  extra_field: 0
  facets: 0
  facets_rest: 0
  facets_searchbox_widget: 0
  facets_summary: 0
  feeds: 0
  feeds_ex: 0
  field: 0
  field_layout: 0
  field_milestone: 0
  field_ui: 0
  file: 0
  filter: 0
  google_analytics: 0
  image: 0
  imagecache_external: 0
  issue_blog_posts: 0
  issue_counter: 0
  issue_events: 0
  issue_library_resources: 0
  issue_news: 0
  issue_organizations: 0
  issue_projects: 0
  jslibrary_usage: 0
  landportal_common: 0
  landportal_content_selection: 0
  landportal_country: 0
  landportal_country_narrative: 0
  landportal_indicators: 0
  landportal_land_voc: 0
  landportal_layouts: 0
  landportal_migration: 0
  landportal_org_filter: 0
  landportal_provider_filter: 0
  landportal_rdf: 0
  landportal_related_blocks: 0
  landportal_remote_block: 0
  landportal_view_coda: 0
  landportal_virtuoso: 0
  language: 0
  latest_news: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_builder_st: 0
  layout_builder_styles: 0
  layout_discovery: 0
  library_resources: 0
  link: 0
  link_attributes: 0
  locale: 0
  lp_issue_indicator: 0
  lp_project_status: 0
  lp_related_content: 0
  lp_related_contentedit: 0
  lp_swiper: 0
  lp_swiper_cycle: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_events: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  migrate: 0
  migrate_drupal: 0
  migrate_file: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  options: 0
  organizations: 0
  page_cache: 0
  path: 0
  path_alias: 0
  programme_impact: 0
  programme_organization: 0
  programme_resources: 0
  project_donor: 0
  project_impact: 0
  project_organization: 0
  project_provider: 0
  project_resources: 0
  projects: 0
  publishing_options: 0
  rdf: 0
  rdf_builder: 0
  rdfui: 0
  recaptcha: 0
  redirect: 0
  redirect_404: 0
  redirect_domain: 0
  rest: 0
  schema_article: 0
  schema_book: 0
  schema_event: 0
  schema_metatag: 0
  schema_organization: 0
  schema_person: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  search_api_solr_admin: 0
  serialization: 0
  simple_sitemap: 0
  social_media: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  translatable_menu_link_uri: 0
  twig_tweak: 0
  update: 0
  user: 0
  view_coda_extra: 0
  views_autosubmit: 0
  views_bootstrap: 0
  views_data_export: 0
  views_templates: 0
  views_timelinejs: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  pathauto: 1
  comment_notify: 10
  content_translation: 10
  views: 10
  minimal: 1000
  eu_cookie_compliance: 1001
theme:
  stable: 0
  landportal: 0
  claro: 0
profile: minimal
