_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    fr: fr
    pt-pt: pt
    es: es
    ru: ru
  domains:
    en: ''
    fr: ''
    pt-pt: ''
    es: ''
    ru: ''
selected_langcode: site_default
