entity_type_groups:
  media:
    country_narrative:
      basic: basic
      advanced: advanced
      open_graph: open_graph
  node:
    country_narrative:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      schema_article: schema_article
    issues:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      schema_article: schema_article
  path_alias:
    path_alias:
      basic: basic
      advanced: advanced
      open_graph: open_graph
  taxonomy_term:
    concepts:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      schema_article: schema_article
    regions:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      schema_article: schema_article
    theme:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      schema_article: schema_article
  user:
    user:
      basic: basic
      advanced: advanced
      open_graph: open_graph
      schema_person: schema_person
tag_trim_method: beforeValue
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_abstract: null
  metatag_maxlength_description: null
  metatag_maxlength_og_title: null
  metatag_maxlength_og_description: null
  metatag_maxlength_og_site_name: null
