label: Media
display:
  default:
    display_title: 'Por defeito'
    display_options:
      title: Media
      fields:
        media_bulk_form:
          action_title: Ação
        thumbnail__target_id:
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: Tipo
          separator: ', '
        uid:
          label: Autor
          separator: ', '
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
          separator: ', '
        changed:
          label: Atualizado
          separator: ', '
        operations:
          label: Operações
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        bundle:
          expose:
            label: Tipo
        status:
          expose:
            label: Verdadeiro
          group_info:
            group_items:
              1:
                title: Publicado
        langcode:
          expose:
            label: Idioma
  media_page_list:
    display_title: Media
    display_options:
      menu:
        title: Media
