display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        changed:
          separator: ', '
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      use_more_text: Mais
  block_1:
    display_title: Block
