display:
  default:
    display_options:
      header:
        area:
          content:
            value: "<p><a href=\"{{'news-events' |t}}\">{{'Notícias &amp; Eventos' |t}}</a> <span>{{ 'Os nossos blogues sobre terras' |t}}</span></p>\r\n"
            format: full_html
