display:
  country_narratives_featured:
    display_options:
      use_more_text: 'Veja todos os últimos portfólios'
      title: 'Últimos portfólios'
  country_narratives_page:
    display_options:
      header:
        result:
          content: 'Exibindo @start - @end de <span class="views-results-total">@total</span>'
