display:
  block_1:
    display_options:
      header:
        area:
          content:
            value: "<h2>Últimos conjuntos de dados estatísticos e espaciais atualizados</h2>\r\n"
            format: filtered_html
