display:
  default:
    display_options:
      use_more_text: 'Mais blogues'
      link_url: /pt/blogs
      header:
        area:
          content:
            value: "<h2><a href=\"/pt/blogs\">Blogues</a></h2>\r\n"
            format: full_html
