display:
  default:
    display_title: 'Por defeito'
    display_options:
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
  block_1:
    display_options:
      block_category: Utilizador
