display:
  default:
    display_title: 'Por defeito'
    display_options:
      fields:
        type:
          label: Tipo
        timestamp:
          label: Data
        message:
          label: Mensagem
        name:
          label: Utilizador
          separator: ', '
        link:
          label: Operações
      pager:
        options:
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page_label: 'Itens por página'
            items_per_page_options_all_label: '- Todos -'
            offset_label: Deslocamento
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      empty:
        area:
          admin_label: 'Não há mensagens no registo.'
          content: 'Não há mensagens no registo.'
      filters:
        type:
          expose:
            label: Tipo
  page:
    display_title: Página
