label: Conteúdo
display:
  default:
    display_title: 'Por defeito'
    display_options:
      title: Conteúdo
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de conteúdo'
          separator: ', '
        name:
          label: Autor
        status:
          label: Estado
          settings:
            format_custom_true: Publicado
        changed:
          label: Atualizado
        operations:
          label: Operações
      pager:
        options:
          tags:
            first: '« Primeira'
            last: 'Última »'
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        title:
          expose:
            label: Título
        type:
          expose:
            label: 'Tipo de conteúdo'
        status:
          expose:
            label: Estado
          group_info:
            group_items:
              1:
                title: Publicado
        langcode:
          expose:
            label: Idioma
  page_1:
    display_title: Página
    display_options:
      menu:
        title: Conteúdo
      tab_options:
        title: Conteúdo
