display:
  default:
    display_options:
      use_more_text: 'Mais eventos'
      link_url: /pt/events
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/events\">Eventos</a></h2>\r\n"
            format: full_html
