display:
  default:
    display_options:
      footer:
        area:
          content:
            value: "<p><span>Projetos ativos financiados por este programa</span></p>\r\n"
            format: full_html
