title: Contact
settings:
  confirmation_message: 'A sua mensagem foi enviada.'
handlers:
  email_confirmation:
    label: 'Confirmação de email'
  email_notification:
    label: 'Notificação por email'
