# Default value.
field.value.additional_info:
  type: mapping
  label: Default value
  mapping:
    title:
      type: string
      label: Title
    description:
      type: text
      label: Description

# Default value.
field.value.additional_information:
  type: mapping
  label: Default value
  mapping:
    title:
      type: string
      label: Title
    description:
      type: text
      label: Description
    format:
      type: string
      label: Format
