additional_html: "<a class=\"a2a_button_email\"></a>\r\n<a class=\"a2a_button_whatsapp\"></a>\r\n<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_linkedin\"></a>"
