display:
  default:
    display_options:
      footer:
        area:
          content:
            value: "<p><span>projets actifs financés par ce programme</span></p>\r\n"
            format: full_html
