display:
  block_2:
    display_options:
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/book/countries\">Pays</a></h2>\r\n"
            format: full_html
  block_3:
    display_options:
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/book/thematic\">Thèmes</a></h2>\r\n"
            format: full_html
  block_4:
    display_options:
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/join-debate\">Participer au Débats </a></h2>\r\n"
            format: full_html
  block_5:
    display_options:
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/debate/events\">Événements</a></h2>\r\n"
            format: full_html
  block_6:
    display_options:
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/book/data\">Données</a></h2>\r\n"
            format: full_html
  block_7:
    display_options:
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/library\">Bibliothèque</a></h2>\r\n"
            format: filtered_html
