display:
  default:
    display_options:
      header:
        area:
          content:
            value: "<p><a href=\"{{'news-events' |t}}\">{{'Actualités &amp; Événements' |t}}</a> <span>{{ 'Nos blogs sur le foncier' |t}}</span></p>\r\n"
            format: full_html
