label: Média
display:
  default:
    display_title: 'Par défaut'
    display_options:
      title: Média
      fields:
        media_bulk_form:
          action_title: Action
        thumbnail__target_id:
          separator: ', '
        name:
          separator: ', '
        bundle:
          label: Type
          separator: ', '
        uid:
          label: Auteur
          separator: ', '
        status:
          label: État
          settings:
            format_custom_true: Publié
          separator: ', '
        changed:
          label: 'Mis à jour'
          separator: ', '
        operations:
          label: Actions
      pager:
        options:
          tags:
            first: '« Premier'
            last: 'Dernier »'
          expose:
            items_per_page_label: 'Éléments par page'
            items_per_page_options_all_label: '- Tout -'
            offset_label: Décalage
      exposed_form:
        options:
          submit_button: Filtrer
          reset_button_label: Réinitialiser
          exposed_sorts_label: 'Trier par'
          sort_asc_label: Asc
          sort_desc_label: Desc
      filters:
        bundle:
          expose:
            label: Type
        status:
          expose:
            label: Vrai
          group_info:
            group_items:
              1:
                title: Publié
        langcode:
          expose:
            label: Langue
  media_page_list:
    display_title: Média
    display_options:
      menu:
        title: Média
