display:
  default:
    display_options:
      header:
        area:
          content:
            value: "<div class=\"voc-name-img\">\r\n<h2>{{ name }}</h2>\r\n<span>{{ field_image_1 }}</span></div>\r\n"
            format: full_html
        result:
          content: 'Affichez @start - @end de <span class="total-counter">@total</span>'
