display:
  default:
    display_options:
      use_more_text: 'Plus de blogues'
      link_url: /fr/blogs
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/blogs\">Blogues</a></h2>\r\n"
            format: full_html
