display:
  default:
    display_options:
      use_more_text: 'Plus d''événements '
      link_url: /fr/events
      header:
        area:
          content:
            value: "<h2><a href=\"/fr/events\">Événements</a></h2>\r\n"
            format: full_html
